### ISSUE TITLE
text-center not work for thead

### ISSUE THREAD

**Issue by fakhamatia** [GhalamborM/bootstrap4-rtl#14]
If use `text-center` for table , text of thead not align center , tbody its OK but thead not work.
Please change 
`th {
    text-align: right;
}`
 to 
`th {
    text-align: inherit;
}`

**Comment by GhalamborM** [comment]
fixed bug in commit  [29f9a817](https://github.com/GhalamborM/bootstrap4-rtl/commit/29f9a817b60e8d7a0e96c8b1c681f7ee9a29aa84)
