### ISSUE TITLE
Border radius for btn-group

### ISSUE THREAD

**Issue by fakhamatia** [GhalamborM/bootstrap4-rtl#15]
Please add class for `btn-group` for RTL
`.btn-group>.btn:not(:last-child):not(.dropdown-toggle) {
    border-top-left-radius: 0;
    border-bottom-left-radius: 0;
}`
left most be right
`.btn-group>.btn-group:not(:first-child)>.btn, .btn-group>.btn:not(:first-child) {
    border-top-right-radius: 0;
    border-bottom-right-radius: 0;
}`
right most be left

use rtl:
![Screenshot from 2019-05-25 15-47-36](https://user-images.githubusercontent.com/20030910/58368678-84239800-7f05-11e9-937d-e4836df60c84.png)

use normal:
![Screenshot from 2019-05-25 15-47-47](https://user-images.githubusercontent.com/20030910/58368685-93a2e100-7f05-11e9-8da5-e6654c1a5ecd.png)

**Comment by GhalamborM** [comment]
fixed in commit [ba55fee](https://github.com/GhalamborM/bootstrap4-rtl/commit/ba55fee3981209934270186cc627d8f9ae2f1328)
