### ISSUE TITLE
have bug in input group

### ISSUE THREAD

**Issue by webineh** [GhalamborM/bootstrap4-rtl#7]
have bug in rtl input group 
https://getbootstrap.com/docs/4.0/components/input-group/

**Comment by GhalamborM** [comment]
fixed bug in commit [21f70fd](https://github.com/GhalamborM/bootstrap4-rtl/commit/21f70fdd0c2591d46873de6ce0b1aea541143691)

**Comment by webineh** [comment]
thank you i will test it soon,

**Comment by webineh** [comment]
very thanks work fine
